[package]
name = "target_tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3", features = ["cargo"]}
object = "0.28"
serde = {version = "1", features = ["derive"]}
serde_json = "1"